### ISSUE TITLE
Transformer is not compatible with coil 2.0

### ISSUE THREAD

**Issue by Mori-Atsushi** [wasabeef/transformers#7]
Coil will make a big breaking change in 2.0.
Now, many `Transformation` for Coil, including `BlurTransformation`, throw an `AbstractMethodError` and do not work with Coil 2.0.

At least the following two changes are required.

* `Transformation.key` is replaced with` Transformation.cacheKey`.
* `BitmapPool` and` PoolableViewTarget` have been removed from the library.

Since Coil 2.0 is alpha, it may changes until the stable release.

Can I make a Pull Request?

**Comment by wasabeef** [comment]
@Mori-Atsushi 
Thank you for teaching me about that. if you make the PR, I'll check that.

**Comment by Qdafengzi** [comment]
update time ?
